version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_USER: 'api'
      POSTGRES_PASSWORD: 'api'
      POSTGRES_DB: 'maepui_core'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'
    ports:
      - '5001:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "api", "-h", "localhost", "-p", "5432", "-d", "maepui_core"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal

  object-storage:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      DEFAULT_BUCKET: maepui-core
    command: server --console-address ":9001" /data
    networks:
      - internal

volumes:
  postgres-data:
  minio-data:

networks:
  internal: