version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_USER: 'api'
      POSTGRES_PASSWORD: 'api'
      POSTGRES_DB: 'maepui_core'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'
    ports:
      - '5001:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "api", "-h", "localhost", "-p", "5432", "-d", "maepui_core"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal

volumes:
  postgres-data:
  minio-data:

networks:
  internal: