service: nestjs-lambda-service

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  stage: staging
  environment:
    NODE_ENV: staging
    TZ: 'Asia/Bangkok' # Corrected line
    MINIO_ENDPOINT: ${env:MINIO_ENDPOINT}
    MINIO_PORT: ${env:MINIO_PORT}
    MINIO_URL: ${env:MINIO_URL}
    MINIO_ACCESS_KEY: ${env:MINIO_ACCESS_KEY}
    MINIO_SECRET_KEY: ${env:MINIO_SECRET_KEY}
    DEFAULT_BUCKET: ${env:DEFAULT_BUCKET}


  region: ap-southeast-1 # Choose your preferred AWS region

functions:
  main:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any